### ISSUE TITLE
Error calling registry.getStatus

### ISSUE THREAD

**Issue by richburdon** [dxos/dashboard#22]
Commented out getStatus in pages/wns inhttps://github.com/dxos/dashboard/pull/21
Causes errors:
```
Cannot query field "node" on type "Status".
Cannot query field "sync" on type "Status".
Cannot query field "validator" on type "Status".
Cannot query field "validators" on type "Status".
Cannot query field "num_peers" on type "Status".
Cannot query field "peers" on type "Status".
Cannot query field "disk_usage" on type "Status".
```

**Comment by ashwinphatak** [comment]
Dashboard config is pointing to https://wns-testnet.dev.wireline.ninja/graphql. After updating those servers to latest master, works now:

<img width="1051" alt="Screen Shot 2020-03-30 at 12 00 27" src="https://user-images.githubusercontent.com/14833/77882191-21fe9680-727e-11ea-98aa-f904f17c8d12.png">

We should discuss how dashboard should behave when using a WNS endpoint that not localhost. My recommendation is to disable start/stop/log in that case.

**Comment by ashwinphatak** [comment]
Closing as status API works now.
