### ISSUE TITLE
Fix app urls

### ISSUE THREAD

**Issue by ccamrobertson** [dxos/dashboard#54]
The `app` URL scheme on the app page is close, but not quite right; it should point to `/app/$publicUrl`:

<img width="1315" alt="Screen Shot 2020-04-14 at 7 49 37 PM" src="https://user-images.githubusercontent.com/1797296/79293713-3ef3b600-7e89-11ea-9881-471734278bfb.png">

Loading apps is also dependent on https://github.com/dxos/dashboard/issues/51.

**Comment by telackey** [comment]
I know this came up in the status, but I'm slightly confused, because that link looks exactly like how it was described that it should look in the call the other day.

What is the "correct" link and how does one know it?

@AFDudley

**Comment by ccamrobertson** [comment]
The "working" way is linking to /app/$publicUrl as described by @elmasse in this issue: https://github.com/dxos/xbox/issues/72

This may be distinct from the "correct" way. My goal is a working stable build of xbox instead of blocking this deliverable on a new `wire app serve`.

**Comment by elmasse** [comment]
@ccamrobertson actually not `/app/$publicUrl`, the publicUrl already contain `/app` for now till we figure out how to properly set publicUrls bound to the app version urls.

**Comment by ccamrobertson** [comment]
@elmasse Ok, so $publicUrl is currently /app/$name? So really dashboard should just show "$publicUrl" without anything else.
